In [1]:
#1.Program to multiply two given arrays of same size element-by-element.
import numpy as np 
num1=([[2,4,5],[2,6,1]]) 
num2=([[3,4,7,],[2,6,1]]) 
print("The first array is") 
print(num1) 
print("The second array is") 
print(num2) 
num3=np.multiply(num1,num2) 
print("After multiplication:") 
print(num3) 

The first array is
[[2, 4, 5], [2, 6, 1]]
The second array is
[[3, 4, 7], [2, 6, 1]]
After multiplication:
[[ 6 16 35]
 [ 4 36  1]]


In [2]:
#2.Program to create an element-wise comparison (greater, greater_equal, lesseer).
import numpy as np 
num1=([[2,4,5],[2,6,1]]) 
num2=([[3,4,7,],[2,6,1]]) 
print("First Array") 
print(num1) 
print("Second array") 
print(num2) 
2 
print("Comparison : greater") 
print(np.greater(num1,num2)) 
print("Comparison : greater_equal") 
print(np.greater_equal(num1,num2)) 
print("Comparison : lesser") 
print(np.less(num1,num2)) 
print("Comparison : less_equal") 
print(np.less_equal(num1,num2)) 
print("Comparison : equal") 
print(np.equal(num1,num2)) 

First Array
[[2, 4, 5], [2, 6, 1]]
Second array
[[3, 4, 7], [2, 6, 1]]
Comparison : greater
[[False False False]
 [False False False]]
Comparison : greater_equal
[[False  True False]
 [ True  True  True]]
Comparison : lesser
[[ True False  True]
 [False False False]]
Comparison : less_equal
[[ True  True  True]
 [ True  True  True]]
Comparison : equal
[[False  True False]
 [ True  True  True]]


In [3]:
#3.Program to create an array of all the even integers from 30 to 70
import numpy as np 
print("Even integers between 30-70") 
a=np.arange(30,71,2) 
print(a) 

Even integers between 30-70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [4]:
#4.Program to create a 3x3 identity matrix 
import numpy as np 
print("3*3 Identity matrix") 
a=np.identity(3,dtype=int) 
print(a) 

3*3 Identity matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
#5.Program to create a vector with values from 0 to 20 and change the sign 
import numpy as np 
print("vector with values from 0 to 20") 
a=np.arange(21) 
print(a) 
print("After changing sign") 
a[(a>15)&(a<19)]*=-1 
print(a) 

vector with values from 0 to 20
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing sign
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15 -16 -17
 -18  19  20]


In [6]:
#6.Program to create a 5x5 zero matrix with elements on the main diagonal
import numpy as np 
a=np.diag([1,2,3,4,5]) 
print("5x5 zero matrix with elements on the main diagonal") 
print(a)

5x5 zero matrix with elements on the main diagonal
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [7]:
#7.Program to compute sum of all elements, sum of each column and sum of each row
import numpy as np 
a=np.array([[1,2,3],[1,2,3]]) 
print("Sum of all elements") 
print(np.sum(a)) 
print("Sum of each column") 
print(np.sum(a,axis=0)) 
print("Sum of each row") 
print(np.sum(a,axis=1)) 

Sum of all elements
12
Sum of each column
[2 4 6]
Sum of each row
[6 6]


In [8]:
#8.Program to save a given array to a text file and load it. 
import numpy as np 
a=np.arange(12).reshape(4,3) 
print("Array:") 
print(a) 
np.savetxt("temp.txt",a) 
res=np.loadtxt("temp.txt") 
print("Array after converted to .txt") 
print(res) 


Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Array after converted to .txt
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [11]:
#10. program to check whether two arrays are equal (element wise) or not
import numpy as np 
print("First array:") 
a=np.array([1,2,3]) 
b=np.array([1,4,3])
print(a) 
print("Second array:") 
print(b) 
b=np.array([1,4,3]) 
print("Element wise equal or not:") 
print(np.equal(a,b)) 

First array:
[1 2 3]
Second array:
[1 4 3]
Element wise equal or not:
[ True False  True]


In [12]:
#11.program to create a 4x4 array with random values, now create a new array after swapping first and last row.
import numpy as np 
a=np.arange(16,dtype=int).reshape(-1,4) 
print("4*4 Array") 
print(a) 
print("array after swapping first and last row") 
a[[0,-1],:]=a[[-1,0],:] 
print(a) 

4*4 Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array after swapping first and last row
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
