In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
data=pd.read_csv('iris.csv')
data.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
x=data.iloc[:,:4]
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
y=data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [ ]:
x_train.head()

sepal_length  sepal_width  petal_length  petal_width
115           6.4          3.2           5.3          2.3
11            4.8          3.4           1.6          0.2
28            5.2          3.4           1.4          0.2
147           6.5          3.0           5.2          2.0
14            5.8          4.0           1.2          0.2

In [ ]:
x_test.head()

sepal_length  sepal_width  petal_length  petal_width
84            5.4          3.0           4.5          1.5
113           5.7          2.5           5.0          2.0
6             4.6          3.4           1.4          0.3
125           7.2          3.2           6.0          1.8
70            5.9          3.2           4.8          1.8

In [ ]:
classifier=KNeighborsClassifier(n_neighbors=5)

In [ ]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica'],
      dtype=object)

In [ ]:
y_test

84     Iris-versicolor
113     Iris-virginica
6          Iris-setosa
125     Iris-virginica
70     Iris-versicolor
102     Iris-virginica
100     Iris-virginica
143     Iris-virginica
54     Iris-versicolor
139     Iris-virginica
4          Iris-setosa
69     Iris-versicolor
83     Iris-versicolor
26         Iris-setosa
78     Iris-versicolor
31         Iris-setosa
58     Iris-versicolor
40         Iris-setosa
49         Iris-setosa
37         Iris-setosa
114     Iris-virginica
12         Iris-setosa
134     Iris-virginica
129     Iris-virginica
1          Iris-setosa
136     Iris-virginica
74     Iris-versicolor
24         Iris-setosa
47         Iris-setosa
130     Iris-virginica
Name: class, dtype: object

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

In [ ]:
result=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(result)

Confusion Matrix
[[11  0  0]
 [ 0  6  2]
 [ 0  0 11]]


In [ ]:
result1=classification_report(y_test,y_pred)
print("Classification Report:")
print(result1)

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.75      0.86         8
 Iris-virginica       0.85      1.00      0.92        11

       accuracy                           0.93        30
      macro avg       0.95      0.92      0.92        30
   weighted avg       0.94      0.93      0.93        30



In [ ]:
result2=accuracy_score(y_test,y_pred)
print("Accuracy:",result2)
print(result2)

Accuracy: 0.9333333333333333
0.9333333333333333
