In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
data=pd.read_csv('iris.csv')
data.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
x=data.iloc[:,:4]
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
y=data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.40)

In [ ]:
x_train.head()

sepal_length  sepal_width  petal_length  petal_width
49            5.0          3.3           1.4          0.2
129           7.2          3.0           5.8          1.6
119           6.0          2.2           5.0          1.5
69            5.6          2.5           3.9          1.1
8             4.4          2.9           1.4          0.2

In [ ]:
x_test.head()

sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
32           5.2          4.1           1.5          0.1
77           6.7          3.0           5.0          1.7
86           6.7          3.1           4.7          1.5
39           5.1          3.4           1.5          0.2

In [ ]:
classifier=GaussianNB()

In [ ]:
classifier.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred= classifier.predict(x_test)

In [ ]:
y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa'

In [ ]:
y_test

0          Iris-setosa
32         Iris-setosa
77     Iris-versicolor
86     Iris-versicolor
39         Iris-setosa
4          Iris-setosa
64     Iris-versicolor
88     Iris-versicolor
101     Iris-virginica
133     Iris-virginica
54     Iris-versicolor
55     Iris-versicolor
144     Iris-virginica
87     Iris-versicolor
22         Iris-setosa
63     Iris-versicolor
43         Iris-setosa
142     Iris-virginica
108     Iris-virginica
45         Iris-setosa
59     Iris-versicolor
60     Iris-versicolor
12         Iris-setosa
67     Iris-versicolor
7          Iris-setosa
30         Iris-setosa
46         Iris-setosa
27         Iris-setosa
132     Iris-virginica
34         Iris-setosa
145     Iris-virginica
9          Iris-setosa
96     Iris-versicolor
37         Iris-setosa
95     Iris-versicolor
15         Iris-setosa
79     Iris-versicolor
112     Iris-virginica
93     Iris-versicolor
84     Iris-versicolor
47         Iris-setosa
110     Iris-virginica
141     Iris-virginica
76     Iris

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score

In [ ]:
result=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(result)

Confusion Matrix:
[[23  0  0]
 [ 0 22  2]
 [ 0  2 11]]


In [ ]:
result1=classification_report(y_test,y_pred)
print("Classification Report:")
print(result1)

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        23
Iris-versicolor       0.92      0.92      0.92        24
 Iris-virginica       0.85      0.85      0.85        13

       accuracy                           0.93        60
      macro avg       0.92      0.92      0.92        60
   weighted avg       0.93      0.93      0.93        60



In [ ]:
result2=accuracy_score(y_test,y_pred)
print("Accuracy Score:")
print(result2)

Accuracy Score:
0.9333333333333333
